export const USER_MANAGEMENT = {
  USER_READ_SELF: "USER_READ_SELF",
  USER_UPDATE_SELF: "USER_UPDATE_SELF",
  USER_DELETE_SELF: "USER_DELETE_SELF",
  USER_CREATE: "USER_CREATE",
  USER_READ_ALL: "USER_READ_ALL",
  USER_UPDATE_ALL: "USER_UPDATE_ALL",
  USER_DELETE_ALL: "USER_DELETE_ALL",
  USER_LIST_ALL: "USER_LIST_ALL",
};
export const ROLE_MANAGEMENT = {
  ROLE_READ: "ROLE_READ",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",
  ROLE_ASSIGN: "ROLE_ASSIGN",
};
export const DOCUMENT_MANAGEMENT = {
  DOCUMENT_READ_SELF: "DOCUMENT_READ_SELF",
  DOCUMENT_CREATE_SELF: "DOCUMENT_CREATE_SELF",
  DOCUMENT_SIGN_SELF: "DOCUMENT_SIGN_SELF",
  DOCUMENT_UPDATE_SELF: "DOCUMENT_UPDATE_SELF",
  DOCUMENT_DELETE_SELF: "DOCUMENT_DELETE_SELF",
  DOCUMENT_SHARE: "DOCUMENT_SHARE",
  DOCUMENT_READ_ALL: "DOCUMENT_READ_ALL",
  DOCUMENT_UPDATE_ALL: "DOCUMENT_UPDATE_ALL",
  DOCUMENT_DELETE_ALL: "DOCUMENT_DELETE_ALL",
};
export const API_ACCESS = {
  API_READ_PUBLIC: "API_READ_PUBLIC",
  API_READ_PROTECTED: "API_READ_PROTECTED",
  API_WRITE_BASIC: "API_WRITE_BASIC",
  API_READ_ALL: "API_READ_ALL",
  API_WRITE_ALL: "API_WRITE_ALL",
  API_ADMIN: "API_ADMIN",
};
export const SESSIONS = {
  SESSION_MANAGE_SELF: "SESSION_MANAGE_SELF",
  SESSION_MANAGE_ALL: "SESSION_MANAGE_ALL",
  SESSION_VIEW_ALL: "SESSION_VIEW_ALL",
  SESSION_TERMINATE_ALL: "SESSION_TERMINATE_ALL",
};
export const INTEGRATIONS = {
  INTEGRATION_USE: "INTEGRATION_USE",
  INTEGRATION_CREATE: "INTEGRATION_CREATE",
  INTEGRATION_UPDATE: "INTEGRATION_UPDATE",
  INTEGRATION_DELETE: "INTEGRATION_DELETE",
  INTEGRATION_KEYS_MANAGE: "INTEGRATION_KEYS_MANAGE",
};
export const AUDIT = {
  AUDIT_READ_SELF: "AUDIT_READ_SELF",
  AUDIT_READ_ALL: "AUDIT_READ_ALL",
  AUDIT_EXPORT: "AUDIT_EXPORT",
  AUDIT_SETTINGS: "AUDIT_SETTINGS",
};
