import {
  AUDIT_MANAGEMENT,
  AUTH_MANAGEMENT,
  DOCUMENT_MANAGEMENT,
  NOTIFICATION_MANAGEMENT,
  REPORT_MANAGEMENT,
  USER_MANAGEMENT,
} from "./permits";
export const ROLE_PERMISSIONS = {
  SUPERADMIN: ["*"],
  ADMIN: [
    ...Object.values(USER_MANAGEMENT),
    ...Object.values(DOCUMENT_MANAGEMENT),
    ...Object.values(REPORT_MANAGEMENT),
    AUTH_MANAGEMENT.TOKEN_ASSIGN,
    AUTH_MANAGEMENT.TOKEN_REVOKE,
    AUDIT_MANAGEMENT.AUDIT_VIEW,
    NOTIFICATION_MANAGEMENT.NOTIFICATION_MANAGE,
  ],
  SUPERVISOR: [
    USER_MANAGEMENT.USER_READ,
    DOCUMENT_MANAGEMENT.DOCUMENT_READ,
    DOCUMENT_MANAGEMENT.DOCUMENT_VERIFY_SIGNATURE,
    REPORT_MANAGEMENT.REPORT_READ,
    REPORT_MANAGEMENT.REPORT_GENERATE,
    AUDIT_MANAGEMENT.AUDIT_VIEW,
  ],
  USER: [
    USER_MANAGEMENT.USER_MANAGE_SELF,
    DOCUMENT_MANAGEMENT.DOCUMENT_SIGN,
    DOCUMENT_MANAGEMENT.DOCUMENT_READ,
    REPORT_MANAGEMENT.REPORT_READ,
  ],
} as const;
